research_gathering_task:
  description: >
    Perform comprehensive research on {topic} using the latest available sources.
    Ensure all information is current and properly sourced with verifiable references.
    Focus on gathering detailed, factual information that provides valuable insights.
    Consider that the current date is {current_date} when assessing information relevance.
  expected_output: >
    A detailed collection of researched information including:
    - Key findings with timestamps
    - Source URLs and citations
    - Relevance assessment for each piece of information
  agent: research_agent

consolidation_task:
  description: >
    Analyze and organize the collected research information into a structured format.
    Identify key themes, patterns, and relationships between different pieces of information.
    Create a logical flow of information that builds a comprehensive understanding of the topic.
  expected_output: >
    A well-organized document containing:
    - Main themes and categories
    - Hierarchical structure of information
    - Connected insights and relationships
    - Summary of key findings
  agent: consolidation_agent

content_creation_task:
  description: >
    Turn the research into a captivating social media post that makes people stop scrolling. 
    Write like you're talking to a friend about something exciting you just discovered.
    Ask a thought-provoking question that makes readers reflect on how this affects them personally.
    End with a clear invitation that makes them want to learn more or take action.
    Keep it conversational, relatable, and avoid technical jargon when possible.
    Make sure it's between 150-200 words and include 3-5 reference links to back up your points.
    
  expected_output: >
    A social media post that includes:
    - 150-200 word engaging content written in a conversational, human tone
    - 3-5 relevant reference links organized neatly at the bottom
    - An attention-grabbing opening that creates curiosity
    - A personal question that helps readers connect with the topic
    - A clear call-to-action that feels natural, not forced
    - 3 Hashtags related to the {topic} 
    - Output shouldn't have any emojis
    - Content should feel like it was written by a human, not AI
  agent: content_creation_agent
